s = set()
n = input("Enter number: ")
s.add(n)
n = input("Enter number: ")
s.add(n)
n = input("Enter number: ")
s.add(n)
n = input("Enter number: ")
s.add(n)
n = input("Enter number: ")
s.add(n)
n = input("Enter number: ")
s.add(n)
n = input("Enter number: ")
s.add(n)
n = input("Enter number: ")
s.add(n)
print(s) #unique numbers will be printed, if same number is added more than once, it will not be added to the set, because set does not allow duplicate values